backend/appointments/routes.py
from flask import Blueprint, abort, jsonify, redirect, render_template, request, url_for
from .services import get_available_slots, get_doctor_by_id, save_appointment, appointment_success


appointment_bp = Blueprint(
    "appointments",
    __name__
)

@appointment_bp.route("/appointments/<int:doctor_id>")
def appointment_list(doctor_id):  
    data = get_doctor_by_id(doctor_id)        
    if not data:
        abort(404)
       
    return render_template(
        "appointments/bookappointment.html", doctor=data['doctor']
    )

@appointment_bp.route("/appointments/<int:doctor_id>/available-slots")
def available_slots(doctor_id): 
    #print("Inside appointment doctor", doctor_id)
    date = request.args.get("date")
    #print("Appointment route: ", doctor_id, date)
    slots = get_available_slots(doctor_id, date)    
    #slots= "1, 2, 3"
    return jsonify(slots)

@appointment_bp.route("/doctors/<int:doctor_id>/book", methods=["GET", "POST"])
def saveappointment(doctor_id):
    if request.method == "POST":        
        appointment_id=save_appointment(doctor_id)                
        data=appointment_success(appointment_id)        
        return render_template("appointments/appointment_success.html", appointment=data        
        )        

@appointment_bp.route("/appointment-success/<int:appointment_id>")
def appointment_success123(appointment_id):
    #appointment1 = appointment_success(appointment_id)
    return render_template(
        "appointments.appointment_success.html", appointment_id = appointment_id          
    )

backend/doctors/__init__.py
from .routes import doctor_bp

backend/doctors/routes.py
from flask import Blueprint, abort, render_template
from .services import get_all_doctors, get_doctor_by_id

doctor_bp = Blueprint(
    "doctors",
    __name__
)

@doctor_bp.route("/doctors")
def doctor_list():
    doctors = get_all_doctors()
    return render_template("doctors/doctor-list.html", doctors=doctors)

@doctor_bp.route("/doctors/<int:doctor_id>")
def doctor_detail(doctor_id):
    doctor_detail = get_doctor_by_id(doctor_id)
    if not doctor_detail:
        abort(404) 

    return render_template(
        "doctors/doctor-detail.html",
        doctor=doctor_detail["doctor"],
        schedules=doctor_detail["schedules"]
    )    
        


backend/templates/doctors/doctor-detail.html
{% extends "base.html" %}

{% block content %}

    <!-- Page Title -->
    <!--<div class="page-title" data-aos="fade">-->
    <div class="page-title">
        <div class="heading container">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>{{ doctor.full_name }} (Profile)</h1>
                        <!--<h2 class="mb-0">{{ doctor.full_name }}</h2>-->
                    </div>
                </div>
            </div>
      </div>      
    </div><!-- End Page Title -->

    <div class="row gy-4">

        <div class="col-md-4">
            <label for="doctor-name">Doctor Name</label>
            <input type="doctor-name" class="form-control readonly-input-box" name="doctor-name" readonly value="{{ doctor.full_name }}">
        </div>

        <div class="col-md-4">
            <label for="gender">Gender</label>
            <input type="gender" class="form-control readonly-input-box" name="gender" readonly value="{{ doctor.gender }}">
        </div>

        <div class="col-md-4">
            <label for="specialization">Specialization</label>
            <input type="specialization" class="form-control readonly-input-box" name="specialization" readonly value="{{ doctor.specialization }}">
        </div>
        
        <div class="col-md-4">
            <label for="qualification">Qualification</label>
            <input type="qualification" class="form-control readonly-input-box" name="qualification" readonly value="{{ doctor.qualification }}">
        </div>
        
        <div class="col-md-4">
            <label for="experience">Experience (Years)</label>
            <input type="experience" class="form-control readonly-input-box" name="experience" readonly value="{{ doctor.experience_years }}">
        </div>        
        <div class="col-md-4">
            <label for="consultation-fee">Consultation Fee</label>
            <input type="consultation-fee" class="form-control readonly-input-box" name="consultation-fee" readonly value="{{ doctor.consultation_fee }}">
        </div>        
    </div>
    <h3 class="mt-4">Visiting Schedule</h3>
    <table class="table table-striped table-dark">
        <thead class="table-header-cus">
            <tr>
                <td>Visit Days</td>
                <td>Start Time</td>
                <td>End Time</td>
                <td>Room No</td>                
            </tr>
        </thead>
        <tbody>
            {% for s in schedules %}
            <tr>
                <td><p>{{ s.visit_days }}</p></td>
                <td><p>{{ s.visit_start_time }}</p></td>
                <td><p>{{ s.visit_end_time }}</p></td>
                <td><p>{{ s.room_no }}</p></td>                
            </tr>
            {% else %}
            <tr>
                <td colspan="5" class="text-center">No schedule available</td>
            </tr>
            {% endfor %}
        </tbody>        
    </table>
    
<a href="{{ url_for('appointments.appointment_list', doctor_id=doctor.doctor_id ) }}" class="btn btn-success mt-3 anchor"> Book Appointment</a>    
<a href="{{ url_for('doctors.doctor_list') }}" class="btn btn-secondary mt-3 anchor">Cancel</a>
    

{% endblock %}

<h1>{{ doctor.full_name }}</h1>

<p><strong>Specialization:</strong> {{ doctor.specialization }}</p>
<p><strong>Experience:</strong> {{ doctor.experience }} years</p>

<a href="{{ url_for('doctors.doctor_list') }}">← Back to Doctors</a>

backend/templates/doctors/doctor-list.html
{% extends "base.html" %}

{% block content %}
    <!-- Page Title -->
    <!--<div class="page-title" data-aos="fade">-->
    <div class="page-title">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>List of Doctors</h1>
                        <p class="mb-0">Grace Clinic always acquire services of best doctors available in the city. Here is the list of doctors associated with Grace Clinic.</p>
                        <p class="mb-0">Click on doctor for setting up an appointment.</p>
                    </div>
                </div>
            </div>
      </div>      
    </div><!-- End Page Title -->
    <!--<section id="contact" class="contact section">-->
        <table class="table table-striped table-dark">
            <thead class="table-header-cus">
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Gender</td>
                    <td>Specialization</td>
                    <td>Qualification</td> 
                    <td>Experience (Years)</td>                                      
                    <!--<td>Action</td> -->
                </tr>
            </thead>
            <tbody>
                {% for doctor in doctors %}
                <tr>                    
                    <td onclick="window.location='{{ url_for('doctors.doctor_detail', doctor_id=doctor.doctor_id) }}'" style="cursor:pointer;"><p>{{ doctor.doctor_id }}</p></td>
                    <td onclick="window.location='{{ url_for('doctors.doctor_detail', doctor_id=doctor.doctor_id) }}'" style="cursor:pointer;"><p>{{ doctor.full_name }}</p></td>
                    <td><p>{{ doctor.gender }}</p></td>
                    <td><p>{{ doctor.specialization }}</p></td>
                    <td><p>{{ doctor.qualification }}</p></td>
                    <td><p>{{ doctor.experience_years }}</p></td>
                    <!--<td><a href="appointment.html" class="btn-get-started">Book an appointment<br></a></td>-->
                </tr>                
                {% endfor %}
            </tbody>
        </table>
        <p style="color:red;">
            Doctors count: {{ doctors | length }}
        </p>
    <!--</section>-->
    <!--</main>-->
<!--</body>-->
{% endblock %}

backend/templates/doctors/doctor_detail_old.html
{% extends "base.html" %}

{% block content %}
<!--<body class="doctor-listing-page">-->
    <!--<main class="main">-->
        <!-- Page Title -->
    <!--<div class="page-title" data-aos="fade">-->
    <div class="page-title">
        <div class="heading container">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>{{ doctor.full_name }} (Profile)</h1>
                        <!--<h2 class="mb-0">{{ doctor.full_name }}</h2>-->
                    </div>
                </div>
            </div>
      </div>      
    </div><!-- End Page Title -->
    <div class="row gy-4">

        <div class="col-md-4">
            <label for="doctor-name">Doctor Name</label>
            <input type="doctor-name" class="form-control readonly-input-box" name="doctor-name" readonly value="{{ doctor.full_name }}">
        </div>

        <div class="col-md-4">
            <label for="gender">Gender</label>
            <input type="gender" class="form-control readonly-input-box" name="gender" readonly value="{{ doctor.gender }}">
        </div>

        <div class="col-md-4">
            <label for="specialization">Specialization</label>
            <input type="specialization" class="form-control readonly-input-box" name="specialization" readonly value="{{ doctor.specialization }}">
        </div>
        
        <div class="col-md-4">
            <label for="qualification">Qualification</label>
            <input type="qualification" class="form-control readonly-input-box" name="qualification" readonly value="{{ doctor.qualification }}">
        </div>
        
        <div class="col-md-4">
            <label for="experience">Experience (Years)</label>
            <input type="experience" class="form-control readonly-input-box" name="experience" readonly value="{{ doctor.experience_years }}">
        </div>        
        <div class="col-md-4">
            <label for="consultation-fee">Consultation Fee</label>
            <input type="consultation-fee" class="form-control readonly-input-box" name="consultation-fee" readonly value="{{ doctor.consultation_fee }}">
        </div>        
    </div>
    
    <h3 class="mt-4">Visiting Schedule</h3>
    <table class="table table-striped table-dark">
        <thead class="table-header-cus">
            <tr>
                <td>Visit Days</td>
                <td>Start Time</td>
                <td>End Time</td>
                <td>Room No</td>                
            </tr>
        </thead>
        <tbody>
            {% for s in schedules %}
            <tr>
                <td><p>{{ s.visit_days }}</p></td>
                <td><p>{{ s.visit_start_time }}</p></td>
                <td><p>{{ s.visit_end_time }}</p></td>
                <td><p>{{ s.room_no }}</p></td>                
            </tr>
            {% else %}
            <tr>
                <td colspan="5" class="text-center">No schedule available</td>
            </tr>
            {% endfor %}
        </tbody>        
    </table>
    <!--<a href="{{ url_for('bookappointment', doctor_id=doctor.doctor_id) }}" class="btn btn-success mt-3 anchor"> Book Appointment</a>-->
    <a href="{{ url_for('doctor') }}" class="btn btn-secondary mt-3 anchor">Cancel</a>

    <!--<section id="contact" class="contact section">-->
        <!--<table class="table table-striped table-dark">
            <tr>
                <thead class="table-header-cus">Doctor ID</th>
                <td>{{ doctor.doctor_id }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ doctor.gender }}</td>
            </tr>
            <tr>
                <th>Specialization</th>
                <td>{{ doctor.specialization }}</td>
            </tr>
            <tr>
                <th>Qualification</th>
                <td>{{ doctor.qualification }}</td>
            </tr>
            <tr>
                <th>Experience</th>
                <td>{{ doctor.experience_years }} years</td>
            </tr>
            <tr>
                <th>Consultation Fee</th>
                <td>{{ doctor.consultation_fee }}</td>
            </tr>
            <tr>
                <th>Visit Days</th>
                <td>{{ doctor.visit_days }}</td>
            </tr>
            <tr>
                <th>Visit Time</th>
                <td>
                  {{ doctor.visit_start_time }} – {{ doctor.visit_end_time }}
                </td>
            </tr>
        </table>-->

    <!--</section>-->
    <!--</main>-->
<!--</body>-->
{% endblock %}

backend/templates/doctors/doctor_list_old.html
{% extends "base.html" %}

{% block content %}
    <!-- Page Title -->
    <!--<div class="page-title" data-aos="fade">-->
    <div class="page-title">
        <div class="heading">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>List of Doctors</h1>
                        <p class="mb-0">Grace Clinic always acquire services of best doctors available in the city. Here is the list of doctors associated with Grace Clinic.</p>
                        <p class="mb-0">Click on doctor for setting up an appointment.</p>
                    </div>
                </div>
            </div>
      </div>      
    </div><!-- End Page Title -->
    <!--<section id="contact" class="contact section">-->
        <table class="table table-striped table-dark">
            <thead class="table-header-cus">
                <tr>
                    <td>ID</td>
                    <td>Name</td>
                    <td>Gender</td>
                    <td>Specialization</td>
                    <td>Qualification</td> 
                    <td>Experience (Years)</td>                                      
                    <!--<td>Action</td> -->
                </tr>
            </thead>
            <tbody>
                {% for doctor in doctors %}
                <tr>                    
                    <td onclick="window.location='{{ url_for('doctor_detail', doctor_id=doctor.doctor_id) }}'" style="cursor:pointer;"><p>{{ doctor.doctor_id }}</p></td>
                    <td onclick="window.location='{{ url_for('doctor_detail', doctor_id=doctor.doctor_id) }}'" style="cursor:pointer;"><p>{{ doctor.full_name }}</p></td>
                    <td><p>{{ doctor.gender }}</p></td>
                    <td><p>{{ doctor.specialization }}</p></td>
                    <td><p>{{ doctor.qualification }}</p></td>
                    <td><p>{{ doctor.experience_years }}</p></td>
                    <!--<td><a href="appointment.html" class="btn-get-started">Book an appointment<br></a></td>-->
                </tr>                
                {% endfor %}
            </tbody>
        </table>
        <p style="color:red;">
            Doctors count: {{ doctors | length }}
        </p>
    <!--</section>-->
    <!--</main>-->
<!--</body>-->
{% endblock %}