backend/appointments/__init__.py
from .routes import appointment_bp

backend/appointments/routes.py
from flask import Blueprint, abort, jsonify, redirect, render_template, request, url_for
from .services import get_available_slots, get_doctor_by_id, save_appointment, appointment_success


appointment_bp = Blueprint(
    "appointments",
    __name__
)

@appointment_bp.route("/appointments/<int:doctor_id>")
def appointment_list(doctor_id):  
    data = get_doctor_by_id(doctor_id)        
    if not data:
        abort(404)
       
    return render_template(
        "appointments/bookappointment.html", doctor=data['doctor']
    )

@appointment_bp.route("/appointments/<int:doctor_id>/available-slots")
def available_slots(doctor_id): 
    #print("Inside appointment doctor", doctor_id)
    date = request.args.get("date")
    #print("Appointment route: ", doctor_id, date)
    slots = get_available_slots(doctor_id, date)    
    #slots= "1, 2, 3"
    return jsonify(slots)

@appointment_bp.route("/doctors/<int:doctor_id>/book", methods=["GET", "POST"])
def saveappointment(doctor_id):
    if request.method == "POST":        
        appointment_id=save_appointment(doctor_id)                
        data=appointment_success(appointment_id)        
        return render_template("appointments/appointment_success.html", appointment=data        
        )        

@appointment_bp.route("/appointment-success/<int:appointment_id>")
def appointment_success123(appointment_id):
    #appointment1 = appointment_success(appointment_id)
    return render_template(
        "appointments.appointment_success.html", appointment_id = appointment_id          
    )

backend/doctors/routes.py
from flask import Blueprint, abort, render_template
from .services import get_all_doctors, get_doctor_by_id

doctor_bp = Blueprint(
    "doctors",
    __name__
)

@doctor_bp.route("/doctors")
def doctor_list():
    doctors = get_all_doctors()
    return render_template("doctors/doctor-list.html", doctors=doctors)

@doctor_bp.route("/doctors/<int:doctor_id>")
def doctor_detail(doctor_id):
    doctor_detail = get_doctor_by_id(doctor_id)
    if not doctor_detail:
        abort(404) 

    return render_template(
        "doctors/doctor-detail.html",
        doctor=doctor_detail["doctor"],
        schedules=doctor_detail["schedules"]
    )    
        


backend/templates/appointments/appointment.html
{% extends "base.html" %}

{% block content %}

<!-- Page Title -->
<!--<div class="page-title" data-aos="fade">-->
<div class="page-title">
    <div class="heading container">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-12">
                    <h1>Welcome To Appointment Page 123</h1>                        
                    <!--<h2>Book Appointment with appointment {{ doctor.full_name }}</h2>-->
                </div>
            </div>
        </div>
    </div>      
</div>
<!-- End Page Title -->

<!--<form method="post" action="{{ url_for('book_appointment', doctor_id=doctor.doctor_id) }}">
    <div class="row gy-4">
        <div class="col-md-12">
            <label>Patient Name</label>
            <input name="patient_name" class="form-control col-md-12" required>
        </div>

        <div class="col-md-6">
            <label>Phone</label>
            <input name="patient_phone" class="form-control col-md-6" required>
        </div>

        <div class="col-md-6">
            <label>Email</label>
            <input name="patient_email" class="form-control col-md-6">
        </div>

        <div class="col-md-6">
            <label>Select Date</label>
            <input type="date" id="appointment_date" name="appointment_date" class="form-control" data-doctor-id="{{ doctor.doctor_id }}">
        </div>

        <div class="col-md-6">
            <label>Available Slots</label>
            <select name="slot" id="slots" class="form-control" required>
                <option value="">Select Slot</option>
            </select>
        </div>
        <button type="submit" class="btn btn-success mt-3 anchor">Confirm Appointment</button>-->
        <!--<a href="{{ url_for('book_appointment', doctor_id=doctor.doctor_id) }}" class="btn btn-success mt-3 anchor">Confirm Appointment</a>-->        
        <a href="{{ url_for('doctor') }}" class="btn btn-secondary mt-3 anchor">Cancel</a>
        <!--<div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <a href="appointment.html" class="btn-get-started">Book an appointment<br></a>            
            </div>
            <button type="submit">Book Appointment</button>
        </div>-->
        
    <!--</div>
  
</form>-->
<script>
document.addEventListener("DOMContentLoaded", function () {

    const dateInput = document.getElementById("appointment_date");
    const today = new Date();
    const yyyy = today.getFullYear();
    const mm = String(today.getMonth() + 1).padStart(2, '0');
    const dd = String(today.getDate()).padStart(2, '0');

    const mm2 = String(today.getMonth() + 1).padEnd(2, '0');
    const dd2 = String(today.getDate() + 7).padStart(2, '0');

    dateInput.min = `${yyyy}-${mm}-${dd}`;

    dateInput.max = `${yyyy}-${mm2}-${dd2}`;

    const slotSelect = document.getElementById("slots");

    if (!dateInput || !slotSelect) {
        console.error("Required elements not found");
        return;
    }

    dateInput.addEventListener("change", function () {
        const date = this.value;
        const doctorId = this.dataset.doctorId;
        
        if (!doctorId || !date) return;

        fetch(`/doctors/${doctorId}/available-slots?date=${date}`)
            .then(res => res.json())
            .then(slots => {            
                slotSelect.innerHTML = '<option value="">Select Slot</option>';

                if (slots.length === 0) {
                    const opt = document.createElement("option");
                    opt.textContent = "No slots available";
                    opt.disabled = true;
                    slotSelect.appendChild(opt);
                    return;
                }

                slots.forEach(s => {
                    const opt = document.createElement("option");
                    opt.value = s[0] + "|" + s[1];
                    opt.textContent = `${s[0]} - ${s[1]}`;
                    slotSelect.appendChild(opt);
                });
            })
            .catch(err => console.error("Fetch error:", err));
        });
    });
</script>
{% endblock %}

backend/templates/appointments/appointment_success.html
{% extends "base.html" %}

{% block content %}
<!--<body class="doctor-listing-page">-->
    <!--<main class="main">-->
        <!-- Page Title -->
    <!--<div class="page-title" data-aos="fade">-->
    <div class="page-title">
        <!--<nav class="breadcrumbs">
            <div class="container">
                <ol>
                    <li><a href="index.html">Home</a></li>
                    <li class="current">Doctors</li>
                </ol>
            </div>
        </nav>-->
        <div class="heading container">
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-12">
                        <h1>Appointment Successful</h1>
                        <h2>Thanks for booking appointment with {{appointment.full_name}}</h2>
                    </div>
                </div>
            </div>
      </div>      
    </div><!-- End Page Title -->
<!--<form method="post">-->
    <div class="row gy-4">
        <div class="col-md-6">
            <label>Appointment No.: </label>
            <input name="patient_name" class="form-control readonly-input-box" readonly value="{{appointment.confirmation_no}}">
        </div>

        <div class="col-md-6">
            <label>Patient Name: </label>
            <input name="patient_name" class="form-control readonly-input-box" readonly value="{{appointment.patient_name}}">
        </div>

        <div class="col-md-4">
            <label>Visit Date: </label>
            <input name="patient_phone" class="form-control readonly-input-box" readonly value="{{ appointment.appointment_date | dd_mmm_yyyy }}">
        </div>

        <div class="col-md-4">
            <label>Visit From: </label>
            <input name="visit_start_time" class="form-control readonly-input-box" readonly value="{{appointment.visit_start_time}}">
        </div>

        <div class="col-md-4">
            <label>Visit Till: </label>
            <input name="visit_end_time" class="form-control readonly-input-box" readonly value="{{appointment.visit_end_time}}">
        </div>
        <div class="col-md-12">
            <label>Important Note</label>
            <input type="comments" name="comments" class="form-control  readonly-input-box" readonly value="Kindly keeping your <strong>Appointment No. with you when you visit the doctor.">
        </div>
        <!--<button class="btn btn-primary mt-3">Confirm Appointment</button>-->
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <!--<a href="appointment.html" class="btn-get-started">Book an appointment<br></a>-->
                <a href="{{ url_for('doctors.doctor_list') }}" class="btn btn-secondary mt-3 anchor">Back</a>
            </div>            
        </div>        
    </div>  
<!--</form>-->
{% endblock %}

backend/templates/appointments/bookappointment.html
{% extends "base.html" %}

{% block content %}

<!-- Page Title -->
<!--<div class="page-title" data-aos="fade">-->
<div class="page-title">
    <div class="heading container">
        <div class="container">
            <div class="row d-flex justify-content-center text-center">
                <div class="col-lg-12">
                    <h1>Welcome To Appointment Page</h1>
                    <h2>Book Appointment with {{ doctor.full_name }}</h2>
                </div>
            </div>
        </div>
    </div>      
</div>
<!-- End Page Title -->

<form method="post" action="{{ url_for('appointments.saveappointment', doctor_id=doctor.doctor_id) }}">
    <div class="row gy-4">
        <label id="doctor_id" hidden="true">Book Appointment with {{ doctor.doctor_id }}</label>        
        <div class="col-md-12">
            <label>Patient Name</label>
            <input name="patient_name" class="form-control col-md-12" required>
        </div>

        <div class="col-md-6">
            <label>Phone</label>
            <input name="patient_phone" class="form-control col-md-6" required>
        </div>

        <div class="col-md-6">
            <label>Email</label>
            <input name="patient_email" class="form-control col-md-6">
        </div>

        <div class="col-md-6">
            <label>Select Date</label>
            <input type="date" id="appointment_date" name="appointment_date" class="form-control" data-doctor-id="{{ doctor.doctor_id }}">
        </div>

        <div class="col-md-6">
            <label>Available Slots</label>
            <select name="slot" id="slots" class="form-control" required>
                <option value="">Select Slot</option>
            </select>
        </div>
        <button type="submit" class="btn btn-success mt-3 anchor">Confirm Appointment</button> 
        <a href="{{ url_for('doctors.doctor_list') }}" class="btn btn-secondary mt-3 anchor">Cancel</a>       
    </div>
  
</form>
<script>
document.addEventListener("DOMContentLoaded", function () {    
    const dateInput = document.getElementById("appointment_date");
    //alert(dateInput);
    const today = new Date();
    const yyyy = today.getFullYear();
    const mm = String(today.getMonth() + 1).padStart(2, '0');
    const dd = String(today.getDate()).padStart(2, '0');

    const mm2 = String(today.getMonth() + 1).padEnd(2, '0');
    const dd2 = String(today.getDate() + 7).padStart(2, '0');

    dateInput.min = `${yyyy}-${mm}-${dd}`;

    dateInput.max = `${yyyy}-${mm2}-${dd2}`;

    const slotSelect = document.getElementById("slots");

    if (!dateInput || !slotSelect) {
        console.error("Required elements not found");
        return;
    }

    dateInput.addEventListener("change", function () {
        const date = this.value;
        const doctorId = this.dataset.doctorId;                
        
        if (!doctorId || !date)         
            return;
        //alert("BEFORE CALL");

        //    fetch(`/doctors/${doctorId}/available-slots?date=${date}`)
        fetch(`/appointments/${doctorId}/available-slots?date=${date}`)
            .then(res => res.json())
            .then(slots => {            
                slotSelect.innerHTML = '<option value="">Select Slot</option>';
                //alert(slots.length)
                if (slots.length === 0) {
                    const opt = document.createElement("option");
                    opt.textContent = "No slots available";
                    opt.disabled = true;
                    slotSelect.appendChild(opt);
                    return;
                }

                slots.forEach(s => {
                    const opt = document.createElement("option");
                    opt.value = s[0] + "|" + s[1];
                    opt.textContent = `${s[0]} - ${s[1]}`;
                    slotSelect.appendChild(opt);
                });
            })
            .catch(err => console.error("Fetch error:", err));
        });
    });
</script>
{% endblock %}

backend/templates/appointments/test.html
<h1>Appointments Template Works</h1>