backend/doctors/routes.py
from flask import Blueprint, abort, render_template
from .services import get_all_doctors, get_doctor_by_id

doctor_bp = Blueprint(
    "doctors",
    __name__
)

@doctor_bp.route("/doctors")
def doctor_list():
    doctors = get_all_doctors()
    return render_template("doctors/doctor-list.html", doctors=doctors)

@doctor_bp.route("/doctors/<int:doctor_id>")
def doctor_detail(doctor_id):
    doctor_detail = get_doctor_by_id(doctor_id)
    if not doctor_detail:
        abort(404) 

    return render_template(
        "doctors/doctor-detail.html",
        doctor=doctor_detail["doctor"],
        schedules=doctor_detail["schedules"]
    )    
        


backend/labtests/routes.py
from flask import Blueprint, abort, render_template
from .services import get_all_labtests, get_labtest_by_id

labtest_bp = Blueprint(
    "labtests",
    __name__
)

@labtest_bp.route("/labtests")
def labtest_list():
    labtests = get_all_labtests()
    return render_template("labtests/labtest-list.html", labtests=labtests)

@labtest_bp.route("/labtests/<int:labtest_id>")
def labtest_detail(labtest_id):
    labtest_detail = get_labtest_by_id(labtest_id)
    if not labtest_detail:
        abort(404) 

    return render_template(
        "labtests/labtest-detail.html",
        labtest=labtest_detail["labtest"]
        #schedules=doctor_detail["schedules"]
    )    
        


backend/opdservices/routes.py
from flask import Blueprint, abort, render_template
from .services import get_all_opdservices, get_opdservice_by_id

opdservice_bp = Blueprint(
    "opdservices",
    __name__
)

@opdservice_bp.route("/opdservices")
def opdservice_list():
    opdservices = get_all_opdservices()
    return render_template("opdservices/opdservice-list.html", opdservices=opdservices)

@opdservice_bp.route("/opdservices/<int:opdservice_id>")
def opdservice_detail(opdservice_id):
    opdservice_detail = get_opdservice_by_id(opdservice_id)
    if not opdservice_detail:
        abort(404) 

    return render_template(
        "opdservices/opdservice-detail.html",
        opdservice=opdservice_detail["opdservice"]
        #schedules=doctor_detail["schedules"]
    )    
        


backend/procedures/routes.py
from flask import Blueprint, abort, render_template
from .services import get_all_procedures, get_procedure_by_id

procedure_bp = Blueprint(
    "procedures",
    __name__
)

@procedure_bp.route("/procedures")
def procedure_list():
    procedures = get_all_procedures()
    return render_template("procedures/procedure-list.html", procedures=procedures)

@procedure_bp.route("/procedures/<int:procedure_id>")
def procedure_detail(procedure_id):
    procedure_detail = get_procedure_by_id(procedure_id)
    if not procedure_detail:
        abort(404) 

    return render_template(
        "procedures/procedure-detail.html",
        procedure=procedure_detail["procedure"]
        #schedules=doctor_detail["schedules"]
    )    
        


backend/vaccines/__init__.py
from .routes import vaccine_bp

backend/vaccines/routes.py
from flask import Blueprint, abort, render_template
from .services import get_all_vaccines, get_vaccine_by_id

vaccine_bp = Blueprint(
    "vaccines",
    __name__
)

@vaccine_bp.route("/vaccines")
def vaccine_list():
    vaccines = get_all_vaccines()
    return render_template("vaccines/vaccine-list.html", vaccines=vaccines)

@vaccine_bp.route("/vaccines/<int:vaccine_id>")
def vaccine_detail(vaccine_id):
    vaccine_detail = get_vaccine_by_id(vaccine_id)
    if not vaccine_detail:
        abort(404) 

    return render_template(
        "vaccines/vaccine-detail.html",
        vaccine=vaccine_detail["vaccine"]
        #schedules=doctor_detail["schedules"]
    )    
        


backend/templates/about.html
{% extends "base.html" %}
{% block content %}
<!-- Page Title -->
    <!--<div class="page-title" data-aos="fade">-->
    <div class="page-title">
        <div class="heading">            
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>About Us</h1>
                        <p class="mb-0">This is about us page.</p>
                    </div>
                </div>
            </div>
      </div>
    </div><!-- End Page Title -->


{% endblock %}

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title class="header sticky-top">Grace Clinic</title>
    <meta name="description" content="">
    <meta name="keywords" content="">

    

    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">

    <!-- Favicons -->    
    <link href="{{ url_for('static', filename='img/favicon.png') }}" rel="icon">
    <link href="{{ url_for('static', filename='img/apple-touch-icon.png') }}" rel="apple-touch-icon">


    <!-- Fonts -->
    <link href="https://fonts.googleapis.com" rel="preconnect">
    <link href="https://fonts.gstatic.com" rel="preconnect" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Inter:wght@100;200;300;400;500;600;700;800;900&family=Cardo:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/bootstrap-icons/bootstrap-icons.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/aos/aos.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/glightbox/css/glightbox.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.css') }}" rel="stylesheet">

    <!-- Main CSS File -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">  

</head>
<body class="index-page">
      <!-- Preloader -->
  <div id="preloader">
    <div class="line"></div>
  </div> 
    <header id="header" class="header d-flex align-items-center sticky-top">
    <div class="container-fluid position-relative d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center me-auto me-xl-0">
        <!-- Uncomment the line below if you also wish to use an image logo -->
        <!-- <img src="assets/img/logo.png" alt=""> -->
        <i class="bi bi-camera"></i>
        <h1 class="sitename">Grace Clinic</h1>
      </a>

        <nav id="navmenu" class="navmenu">
            <ul>
                <li class="dropdown"><a><span>Home</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                    <ul>
                    <li><a href="{{ url_for('introduction') }}">Introduction</a></li>
                        <li><a href="{{ url_for('accreditions.accredition_list') }}">Accreditions</a></li>
                        <li><a href="{{ url_for('doctors.doctor_list') }}">Doctors</a></li>
                        <li><a href="{{ url_for('about') }}">About Clinic</a></li>            
                    </ul>
                </li>
                <li class="dropdown"><a><span>Services</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                    <ul>
                        <li><a href="{{url_for('opdservices.opdservice_list')}}">OPD Services</a></li>
                        <li><a href="{{url_for('labtests.labtest_list')}}">Lab</a></li>
                        <li><a href="{{url_for('procedures.procedure_list')}}">Procedures</a></li>
                        <li><a href="{{ url_for('vaccines.vaccine_list') }}">Vaccines</a></li>
                    </ul>
                </li>
                <li class="dropdown"><a><span>Policies</span> <i class="bi bi-chevron-down toggle-dropdown"></i></a>
                    <ul>
                        <li><a href="">Policies</a></li>                        
                    </ul>
                </li>                     
            </ul>
            <i class="mobile-nav-toggle d-xl-none bi bi-list"></i>
        </nav>

        <div class="header-social-links">
            <a href="#" class="twitter"><i class="bi bi-twitter-x"></i></a>
            <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
        </div>
    </div>
</header>
    <main>
        {% block content %}        
        {% endblock %}        
    </main>
    <!-- ======= Vendor JS ======= -->
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/aos/aos.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/glightbox/js/glightbox.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/swiper/swiper-bundle.min.js') }}"></script>

    <!-- Main JS -->
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>
</html>

backend/templates/footer.html
<footer id="footer" class="footer">

    <div class="container">
      <div class="copyright text-center ">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">PhotoFolio</strong> <span>All Rights Reserved</span></p>
      </div>
      <div class="social-links d-flex justify-content-center">
        <a href=""><i class="bi bi-twitter-x"></i></a>
        <a href=""><i class="bi bi-facebook"></i></a>
        <a href=""><i class="bi bi-instagram"></i></a>
        <a href=""><i class="bi bi-linkedin"></i></a>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a>
      </div>
    </div>

  </footer>

  <!-- Scroll Top -->
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Preloader -->
  <div id="preloader">
    <div class="line"></div>
  </div>

backend/templates/index.html
{% extends "base.html" %}
{% block content %}

<!--<main class="main">-->
  <section id="hero" class="hero section">
      <div class="container">
        <div class="row justify-content-center">
          <!--<div class="col-lg-6 text-center" data-aos="fade-up" data-aos-delay="100">-->
          <div class="col-lg-6 text-center">
            <h2><span>This is</span><span >Grace Clinic</span> A Clinic with highly qualified<span> Doctors from New York City</span></h2>
            <p>With more than 30 years of experience in the field of medicine, we can help you out in your fight against any disease</p>
            <a href="{{ url_for('doctors.doctor_list') }}" class="btn-get-started">Book an appointment<br></a>            
          </div>    
          <!--</div>-->
        </div>
      </div>
  </section><!-- /Hero Section -->
<!--</main>-->
<!--<section id="hero" class="hero section">
  <div class="container text-center">
    <h2>Welcome to <span>Grace Clinic</span></h2>    
    <p>With more than 30 years of experience in the field of medicine, we can help you out in your fight against any disease</p>
    <a href="#" class="btn btn-primary">Book Appointment</a>
  </div>
</section>-->
<section id="gallery" class="gallery section">
  <!--<div class="container-fluid" data-aos="fade-up" data-aos-delay="100">-->
  <div class="container-fluid">
    <div class="row gy-4 justify-content-center">
      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-1.jpg') }}" class="img-fluid" alt="Introduction">
            <div class="gallery-links d-flex align-items-center justify-content-center">
              <!--<a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>-->
              <!--<a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>-->
              <a href="{{ url_for('introduction') }}" class="details-link"><i class="bi bi-link-45deg"></i>Introduction</a>
            </div>
        </div>
      </div><!-- End Gallery Item -->
      
      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-2.jpg') }}" class="img-fluid" alt="">
          <div class="gallery-links d-flex align-items-center justify-content-center">
            <a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>
            <a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>
            <a href="{{ url_for('accreditions.accredition_list') }}" class="details-link"><i class="bi bi-link-45deg"></i>Accreditions</a>
          </div>
        </div>
      </div><!-- End Gallery Item -->

      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-3.jpg') }}" class="img-fluid" alt="">
          <div class="gallery-links d-flex align-items-center justify-content-center">
            <a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>
            <a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>
            <a href="{{ url_for('doctors.doctor_list') }}" class="details-link"><i class="bi bi-link-45deg"></i>Doctors</a>
          </div>
        </div>
      </div><!-- End Gallery Item -->  
      
      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-4.jpg') }}" class="img-fluid" alt="">
          <div class="gallery-links d-flex align-items-center justify-content-center">
            <a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>
            <!--<a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>-->
            <a href="{{ url_for('about') }}" class="details-link"><i class="bi bi-link-45deg"></i>About Clinic</a>
          </div>
        </div>
      </div><!-- End Gallery Item --> 

      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-5.jpg') }}" class="img-fluid" alt="">
          <div class="gallery-links d-flex align-items-center justify-content-center">
            <!--<a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>-->
            <!--<a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>-->
            <a href="{{ url_for('opdservices.opdservice_list') }}" class="details-link"><i class="bi bi-link-45deg"></i>OPD Services</a>
          </div>
        </div>
      </div><!-- End Gallery Item -->
      
      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-6.jpg') }}" class="img-fluid" alt="">
          <div class="gallery-links d-flex align-items-center justify-content-center">
            <!--<a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>-->
            <!--<a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>-->
            <a href="{{ url_for('labtests.labtest_list') }}" class="details-link"><i class="bi bi-link-45deg"></i>Lab Tests</a>
          </div>
        </div>
      </div><!-- End Gallery Item -->
      
      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-7.jpg') }}" class="img-fluid" alt="">
          <div class="gallery-links d-flex align-items-center justify-content-center">
            <!--<a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>-->
            <!--<a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>-->            
            <a href="{{ url_for('procedures.procedure_list') }}" class="details-link"><i class="bi bi-link-45deg"></i>Procedures</a>
          </div>
        </div>
      </div><!-- End Gallery Item -->  

      <div class="col-xl-3 col-lg-4 col-md-6">
        <div class="gallery-item h-100">
          <img src="{{ url_for('static', filename='img/gallery/gal-8.jpg') }}" class="img-fluid" alt="">
          <div class="gallery-links d-flex align-items-center justify-content-center">
            <!--<a href="assets/img/gallery/gallery-1.jpg" title="Gallery 1" class="glightbox preview-link"><i class="bi bi-arrows-angle-expand"></i></a>-->
            <!--<a href="gallery-single.html" class="details-link"><i class="bi bi-link-45deg"></i></a>-->
            <a href="{{ url_for('vaccines.vaccine_list') }}" class="details-link"><i class="bi bi-link-45deg"></i>Vaccines</a>
          </div>
        </div>
      </div><!-- End Gallery Item -->       
  </div>  
    <!--</div>-->
</section>
<footer id="footer" class="footer">
    <div class="container">
      <div class="copyright text-center ">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">PhotoFolio</strong> <span>All Rights Reserved</span></p>
      </div>
      <div class="social-links d-flex justify-content-center">
        <a href=""><i class="bi bi-twitter-x"></i></a>
        <a href=""><i class="bi bi-facebook"></i></a>
        <a href=""><i class="bi bi-instagram"></i></a>
        <a href=""><i class="bi bi-linkedin"></i></a>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a>
      </div>
    </div>
  </footer>
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
{% endblock %}

backend/templates/introduction.html
{% extends "base.html" %}

{% block content %}
    <!-- Page Title -->
    <!--<div class="page-title" data-aos="fade">-->
    <div class="page-title">
        <div class="heading">            
            <div class="container">
                <div class="row d-flex justify-content-center text-center">
                    <div class="col-lg-8">
                        <h1>Introduction</h1>
                        <p class="mb-0">Grace Clinic has been proudly serving the people of New York for over 30 years, providing reliable and compassionate basic healthcare services to the community. With a strong focus on patient care and accessibility, Grace Clinic offers comprehensive Outpatient Department (OPD) services, on-site laboratory facilities, minor medical procedures, and a full range of vaccination services.
                            Backed by experienced medical professionals and modern facilities, Grace Clinic is committed to delivering quality healthcare in a comfortable and trusted environment.
                        </p>
                        <div class="hero section">
                            <div class="container">
                                <div class="row justify-content-center">
                                    <div class="col-lg-6 text-center">
                                        <a href="{{ url_for('doctors.doctor_list') }}" class="btn-get-started">Book an appointment<br></a>  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>            
      </div>
    </div><!-- End Page Title -->
    <!-- Contact Section -->
    <section id="contact" class="contact section">
        <div class="container" >        <!--data-aos="fade-up" data-aos-delay="100"-->
            <div class="info-wrap" > <!--data-aos="fade-up" data-aos-delay="200"-->
                <div class="row gy-5">
                    <div class="col-lg-4">
                        <div class="info-item d-flex align-items-center">
                            <i class="bi bi-geo-alt flex-shrink-0"></i>
                            <div>
                                <h3>Clinic Introduction</h3>
                                <p>Add Clinic Introduction</p>
                            </div>
                        </div>
                    </div><!-- End Info Item -->
                    <div class="col-lg-4">
                        <div class="info-item d-flex align-items-center">
                            <i class="bi bi-telephone flex-shrink-0"></i>
                            <div>
                                <h3>Specialties / services highlights</h3>
                                <p>Add Specialties / services highlights</p>
                            </div>
                        </div>
                    </div><!-- End Info Item -->

                    <div class="col-lg-4">
                        <div class="info-item d-flex align-items-center">
                            <i class="bi bi-envelope flex-shrink-0"></i>
                            <div>
                                <h3>Doctor availability summary</h3>
                                <p>Add Doctor availability summary</p>
                            </div>
                        </div>
                    </div><!-- End Info Item -->
                </div>
            </div>

            <form action="forms/appointment.php" method="post" class="php-email-form"> <!--data-aos="fade-up" data-aos-delay="300"-->
                <div class="row gy-4">
                    <div class="col-md-12 dropdown">
                        <div class="col-md-12 text-center">
                            <div class="loading">Loading</div>
                            <div class="error-message"></div>
                            <div class="sent-message">Your message has been sent. Thank you!</div>

                            <button type="submit">Book Appointment111</button>                            
                        </div>
                    </div>
                    
            </form><!-- End Contact Form -->
            
        </div>
    </section><!-- /Contact Section -->
    </div>      
    <!--</div>-->

<footer id="footer" class="footer">
    <div class="container">
      <div class="copyright text-center ">
        <p>© <span>Copyright</span> <strong class="px-1 sitename">PhotoFolio</strong> <span>All Rights Reserved</span></p>
      </div>
      <div class="social-links d-flex justify-content-center">
        <a href=""><i class="bi bi-twitter-x"></i></a>
        <a href=""><i class="bi bi-facebook"></i></a>
        <a href=""><i class="bi bi-instagram"></i></a>
        <a href=""><i class="bi bi-linkedin"></i></a>
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you've purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: [buy-url] -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a>
      </div>
    </div>
  </footer>
  <a href="#" id="scroll-top" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

{% endblock %}

backend/templates/lab123.html
{% extends "base.html" %}

{% block content %}
<h2>Available Lab Tests</h2>

{% for test in tests %}
<div class="card">
    <h3>{{ test.test_name }}</h3>
    <p>{{ test.description }}</p>
</div>
{% endfor %}

{% endblock %}

backend/templates/patients.html
{% extends "base.html" %}

{% block content %}
<h2>Patients</h2>

{% for patient in patients %}
<div class="card">
    <h3>{{ patient.name }}</h3>
    <p>{{ patient.age }}</p>
</div>
{% endfor %}

{% endblock %}

backend/templates/vaccine.html
{% extends "base.html" %}

{% block content %}
<h2>Our Vaccines</h2>

{% endblock %}

backend/templates/visits.html
{% extends "base.html" %}

{% block content %}
<h2>Patients Visits</h2>

{% for visit in visits %}
<div class="card">
    <h3>{{ visit.patint-id }}</h3>
    <p>{{ visit.visit_date }}</p>
    <p>{{ visit.doctor_name }}</p>
    <p>{{ visit.diagnosis, prescription }}</p>
    <p>{{ visit.prescription }}</p>
</div>
{% endfor %}

{% endblock %}